name: linting

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  linting:
    strategy:
      fail-fast: true
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - uses: psf/black@stable
        with:
          options: "--check --verbose --diff --color"
      - uses: isort/isort-action@master
        with:
          configuration: "--check-only --diff"
      - name: Analysing the code style
        run: |
          tox -e codestyle
      - name: Analysing the docstyle
        run: |
          tox -e docstyle
      - name: Analysing the code with mypy
        run: |
          tox -e types
      - name: Analysing the code with pylint/flake
        run: |
          tox -e errors
