name: Tests

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test-python:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Analysing the code with mypy
        continue-on-error: true
        run: |
          tox -e types
      - name: Analysing the code with pylint/flake
        continue-on-error: true
        run: |
          tox -e errors
      - name: Run pytests with coverage
        continue-on-error: true
        run: |
          tox -e test -- --junitxml=results.xml tests/
      - name: Convert coverage
        run: |
          tox -e coverage
      - uses: codecov/codecov-action@v2
        with:
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
